<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\..\Shared\KPI.Shared.ApplicationService\KPI.Shared.ApplicationService.csproj" />
    <ProjectReference Include="..\KPI.Infrastructure\KPI.Infrastructure.csproj" />
  </ItemGroup>

</Project>
